[[redirects]]
  from = "/_next/image/*"
  to = "/.netlify/images"
  status = 200
  force = true
  query = { url = ":url", w = ":width", q = ":quality" }

[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

[functions]
  node_bundler = "esbuild"

[[plugins]]
  package = "@netlify/plugin-nextjs" 